# This is a basic workflow to help you get started with Actions

name: Rickroll

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: read
        id: readfile
        uses: juliangruber/read-file-action@v1
        with:
          path: api/count.txt
          trim: true
      - name: remove
        run: rm api/count.txt
      - name: modif
        run: |
          let x=$((${{ steps.readfile.outputs.content }}+1))
          echo "$x" >> api/count.txt
      - name: commit
        run: |
          git config --local user.email "70614549+liimee@users.noreply.github.com"
          git config --local user.name "liimee"
          git add ./api/count.txt
          git commit -m "HEH, I RICKROLLED SOMEONE 😛"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.TEST }}
          force: true
